apereo_sso/src/main/java/org/jasig/cas/zk/entity/ZkUserGredential.java
package org.jasig.cas.zk.entity;

import java.io.Serializable;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.jasig.cas.authentication.Credential;

public class ZkUserGredential implements Credential,Serializable {

	
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@NotNull
	@Size(min=1, message = "required.username")
	private String username;
	@NotNull
	@Size(min=1, message = "required.password")
	private String password;
	private String userinfo;
	
	public ZkUserGredential(){
		
	}
	
	public ZkUserGredential(String username,String password,String userinfo){
		this.username = username;
		this.password = password;
		this.userinfo = userinfo;
		
	}
	
	
	public String getUsername() {
		return username;
	}
	
	public void setUsername(String username) {
		this.username = username;
	}
	
	public String getPassword() {
		return password;
	}
	
	public void setPassword(String password) {
		this.password = password;
	}

	public String getUserinfo() {
		return userinfo;
	}

	public void setUserinfo(String userinfo) {
		this.userinfo = userinfo;
	}


	@Override
	public String getId() {
		return username;
	}
	
	@Override
    public boolean equals(final Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        final ZkUserGredential that = (ZkUserGredential) o;

        if (password != null ? !password.equals(that.password) : that.password != null) {
            return false;
        }

        if (username != null ? !username.equals(that.username) : that.username != null) {
            return false;
        }
        
        if (userinfo !=null ? !userinfo.equals(that.userinfo) : that.userinfo !=null){
        	return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder()
                .append(username)
                .append(password)
                .append(userinfo)
                .toHashCode();
    }
}

apereo_sso/src/main/webapp/WEB-INF/view/jsp/protocol/2.0/casProxyFailureView.jsp
<%@ page session="false" contentType="application/xml; charset=UTF-8" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
    <cas:proxyFailure code='${code}'>
            ${fn:escapeXml(description)}
    </cas:proxyFailure>
</cas:serviceResponse>

apereo_sso/src/main/webapp/WEB-INF/view/jsp/protocol/2.0/casProxySuccessView.jsp
<%@ page session="false" contentType="application/xml; charset=UTF-8" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
    <cas:proxySuccess>
        <cas:proxyTicket>${fn:escapeXml(ticket)}</cas:proxyTicket>
    </cas:proxySuccess>
</cas:serviceResponse>

apereo_sso/src/main/webapp/WEB-INF/view/jsp/protocol/2.0/casServiceValidationFailure.jsp
<%@ page session="false" contentType="application/xml; charset=UTF-8" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
    <cas:authenticationFailure code='${code}'>
            ${fn:escapeXml(description)}
    </cas:authenticationFailure>
</cas:serviceResponse>

apereo_sso/src/main/webapp/WEB-INF/view/jsp/protocol/2.0/casServiceValidationSuccess.jsp
<%@ page session="false" contentType="application/xml; charset=UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
    <cas:authenticationSuccess>
        <cas:user>${fn:escapeXml(principal.id)}</cas:user>
        <c:choose>
			<c:when test="${not empty principal.attributes.parentId}">
				<cas:attributes>
			        <cas:userId>${fn:escapeXml(principal.attributes.userId)}</cas:userId>
			        <cas:parentId>${fn:escapeXml(principal.attributes.parentId)}</cas:parentId>
			        <cas:companyId>${fn:escapeXml(principal.attributes.companyId)}</cas:companyId>
					<cas:lastLoginDate>${fn:escapeXml(principal.attributes.lastLoginDate)}</cas:lastLoginDate>
					<cas:mobilePhone>${fn:escapeXml(principal.attributes.mobilePhone)}</cas:mobilePhone>
					<cas:contactNameCn>${fn:escapeXml(principal.attributes.contactNameCn)}</cas:contactNameCn>
					<cas:auditStatus>${fn:escapeXml(principal.attributes.auditStatus)}</cas:auditStatus>
		        </cas:attributes>
			</c:when>
			<c:otherwise>
				<cas:attributes>
			        <cas:userId>${fn:escapeXml(principal.attributes.userId)}</cas:userId>
					<cas:userName>${fn:escapeXml(principal.attributes.contact)}</cas:userName>
		        </cas:attributes>
			</c:otherwise>
		</c:choose>
        
        <c:if test="${not empty pgtIou}">
            <cas:proxyGrantingTicket>${pgtIou}</cas:proxyGrantingTicket>
        </c:if>
        <c:if test="${fn:length(chainedAuthentications) > 0}">
            <cas:proxies>
                <c:forEach var="proxy" items="${chainedAuthentications}" varStatus="loopStatus" begin="0" end="${fn:length(chainedAuthentications)}" step="1">
                    <cas:proxy>${fn:escapeXml(proxy.principal.id)}</cas:proxy>
                </c:forEach>
            </cas:proxies>
        </c:if>
    </cas:authenticationSuccess>
</cas:serviceResponse>